VIDEO_PATH = ""
WORKING_DIRECTORY_NAME = 'working_directory'
OUT_EXTRACT_IMAGES = 'out_images'
OUT_EXTRACT_IMAGES_CLEAN = 'out_images_clean'
VIDEO_EXTRACT_RATE_EVERY_FRAME = 24 # Every 24 Frames
#VIDEO_SCREEN_TO_CROP = 
HARDSUB_LANGUAGE = "fra"
VIDEO_EXTENSION_ARRAY = ['mp4','mkv','avi']